baseurl = "https://www.sumeetnaik.com"
title = "Sumeet Naik"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "sumeetnaik"

[params]
  author = "Sumeet Naik"
  info = "Backend, Cloud & Coffee"
  description = "Sumeet Naik's personal website"
  keywords = "Backend,Cloud,Engineer,Blog"
  avatarurl = "images/avatar.png"
  #gravatar = ""

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[params.cloudflare]
    token = "e8a1026859c841c1b74c53c570abf08a"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "GitHub"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/sumeetweb"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/sumeetnaik19/"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/sumeetweb"

[[params.social]]
  name = "Ko-fi"
  icon = "fa fa-buymeacoffee fa-2x"
  weight = 4
  url = "https://ko-fi.com/sumeet"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Resume"
  weight = 2
  url = "tech-resume/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true